import { useEffect, useState } from "react";
import "./App.css";

const SAMPLE_JOB_DESCRIPTIONS = [
  {
    title: "Python Full Stack Developer",
    text: "Looking for a Python Full Stack Developer with skills in Python, Django, Django REST Framework, React, JavaScript, HTML, CSS, SQL, REST API, Git, GitHub, Postman, authentication, and deployment. Candidate should be able to build frontend pages, backend APIs, and connect React with Django REST Framework.",
  },
  {
    title: "Backend API Developer",
    text: "Hiring Backend Developer Trainee with knowledge of Python, Django, Django REST Framework, SQL, PostgreSQL, REST API, JWT authentication, Postman, Git, GitHub, CRUD APIs, database design, and backend development.",
  },
  {
    title: "Frontend React Developer",
    text: "We are looking for a Frontend Developer fresher with strong knowledge of HTML, CSS, JavaScript, React, Bootstrap, Tailwind, Git, GitHub, REST API integration, responsive design, and problem solving skills.",
  },
  {
    title: "Java Spring Boot Developer",
    text: "We are hiring a Java Spring Boot Developer with knowledge of Java, Spring Boot, Hibernate, Microservices, AWS, Docker, Kubernetes, MongoDB, REST API, Git, GitHub, and database design.",
  },
];

function App() {
  const [activePage, setActivePage] = useState("analyzer");

  const [resume, setResume] = useState(null);
  const [jobDescription, setJobDescription] = useState("");
  const [result, setResult] = useState(null);

  const [history, setHistory] = useState([]);
  const [loadingHistory, setLoadingHistory] = useState(false);

  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");
  const [successMessage, setSuccessMessage] = useState("");

  const loadHistory = () => {
    setLoadingHistory(true);

    fetch("http://127.0.0.1:8000/api/history/")
      .then((response) => response.json())
      .then((data) => {
        setHistory(Array.isArray(data) ? data : []);
        setLoadingHistory(false);
      })
      .catch(() => {
        setLoadingHistory(false);
      });
  };

  useEffect(() => {
    loadHistory();
  }, []);

  const totalScans = history.length;

  const averageScore =
    history.length > 0
      ? (
          history.reduce((total, item) => total + Number(item.match_score), 0) /
          history.length
        ).toFixed(2)
      : 0;

  const bestScore =
    history.length > 0
      ? Math.max(...history.map((item) => Number(item.match_score)))
      : 0;

  const currentScore = result ? Number(result.analysis.match_score) : 0;

  const getScoreLabel = (score) => {
    const numericScore = Number(score);

    if (numericScore >= 75) return "Strong Match";
    if (numericScore >= 50) return "Moderate Match";
    return "Needs Improvement";
  };

  const getScoreClass = (score) => {
    const numericScore = Number(score);

    if (numericScore >= 75) return "strong";
    if (numericScore >= 50) return "moderate";
    return "weak";
  };

  const normalizeList = (value) => {
    if (!value) return [];
    if (Array.isArray(value)) return value.filter(Boolean);

    return String(value)
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  };

  const getRoadmapList = (analysis) => {
    if (!analysis) return [];

    if (Array.isArray(analysis.roadmap_list)) {
      return analysis.roadmap_list.filter(Boolean);
    }

    if (analysis.roadmap) {
      return String(analysis.roadmap)
        .split("|")
        .map((item) => item.trim())
        .filter(Boolean);
    }

    return [];
  };

  const buildReportText = (analysis, resumeSkills = [], jdSkills = []) => {
    const matchedSkills = normalizeList(analysis.matched_skills_list).join(", ");
    const missingSkills = normalizeList(analysis.missing_skills_list).join(", ");
    const roadmapList = getRoadmapList(analysis);
    const detectedResumeSkills = normalizeList(resumeSkills).join(", ");
    const requiredJdSkills = normalizeList(jdSkills).join(", ");

    return `ResumeSkill Analyzer - Resume Match Report
=========================================

Match Score: ${analysis.match_score}%
Status: ${getScoreLabel(analysis.match_score)}

Matched Skills:
${matchedSkills || "None"}

Missing Skills:
${missingSkills || "None"}

Skills Detected From Resume:
${detectedResumeSkills || "Not available"}

Skills Required In Job Description:
${requiredJdSkills || "Not available"}

Suggested Learning Roadmap:
${
  roadmapList.length > 0
    ? roadmapList.map((item, index) => `${index + 1}. ${item}`).join("\n")
    : "No roadmap available."
}

Generated By:
ResumeSkill Analyzer

Note:
This report is generated by comparing technical skills found in the resume with the skills required in the job description.
`;
  };

  const downloadReport = (reportData, source = "current") => {
    let reportText = "";

    if (source === "current") {
      reportText = buildReportText(
        reportData.analysis,
        reportData.resume_skills,
        reportData.job_description_skills
      );
    } else {
      reportText = buildReportText(reportData);
    }

    const blob = new Blob([reportText], { type: "text/plain" });
    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");
    link.href = url;
    link.download = `ResumeSkill_Report_${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    URL.revokeObjectURL(url);
  };

  const copyReport = async (reportData, source = "current") => {
    let reportText = "";

    if (source === "current") {
      reportText = buildReportText(
        reportData.analysis,
        reportData.resume_skills,
        reportData.job_description_skills
      );
    } else {
      reportText = buildReportText(reportData);
    }

    try {
      await navigator.clipboard.writeText(reportText);
      setSuccessMessage("Report copied to clipboard.");
      setTimeout(() => setSuccessMessage(""), 2500);
    } catch {
      setError("Could not copy report. Please try again.");
    }
  };

  const handleAnalyze = (e) => {
    e.preventDefault();

    if (!resume) {
      setError("Please upload your resume PDF.");
      return;
    }

    if (!jobDescription.trim()) {
      setError("Please paste the job description.");
      return;
    }

    setLoading(true);
    setError("");
    setSuccessMessage("");
    setResult(null);

    const formData = new FormData();
    formData.append("resume", resume);
    formData.append("job_description", jobDescription);

    fetch("http://127.0.0.1:8000/api/analyze/", {
      method: "POST",
      body: formData,
    })
      .then(async (response) => {
        const data = await response.json();

        if (!response.ok) {
          throw new Error(data.error || "Analysis failed");
        }

        return data;
      })
      .then((data) => {
        setResult(data);
        setLoading(false);
        setSuccessMessage("Resume analyzed successfully.");
        loadHistory();
      })
      .catch((err) => {
        setError(
          err.message ||
            "Failed to analyze resume. Check backend server or PDF file."
        );
        setLoading(false);
      });
  };

  const resetAnalyzer = () => {
    setResume(null);
    setJobDescription("");
    setResult(null);
    setError("");
    setSuccessMessage("");

    const fileInput = document.getElementById("resume-upload");
    if (fileInput) fileInput.value = "";
  };

  const Navbar = () => (
    <nav className="navbar">
      <div className="brand">
        <div className="logo">
          <span className="logo-doc"></span>
          <span className="logo-check">✓</span>
        </div>

        <div>
          <h2>ResumeSkill Analyzer</h2>
          <p>Resume × Job Description Matcher</p>
        </div>
      </div>

      <div className="nav-actions">
        <button
          className={activePage === "analyzer" ? "active-nav" : ""}
          onClick={() => {
            setActivePage("analyzer");
            setError("");
            setSuccessMessage("");
          }}
        >
          Analyzer
        </button>

        <button
          className={activePage === "history" ? "active-nav" : ""}
          onClick={() => {
            setActivePage("history");
            setError("");
            setSuccessMessage("");
            loadHistory();
          }}
        >
          History
        </button>
      </div>
    </nav>
  );

  if (activePage === "history") {
    return (
      <div className="app">
        <div className="black-gradient"></div>
        <Navbar />

        <section className="history-page">
          <div className="page-heading">
            <span className="badge">Dashboard</span>

            <h1>Analysis History</h1>

            <p>
              Track your previous resume scans, match scores, matched skills,
              missing skills, and downloadable reports.
            </p>
          </div>

          {successMessage && <p className="success-message">{successMessage}</p>}

          <div className="dashboard-grid">
            <div className="dashboard-card">
              <span>Total Scans</span>
              <h3>{totalScans}</h3>
              <p>Resume reports generated</p>
            </div>

            <div className="dashboard-card">
              <span>Average Score</span>
              <h3>{averageScore}%</h3>
              <p>Across all analysis reports</p>
            </div>

            <div className="dashboard-card">
              <span>Best Score</span>
              <h3>{bestScore}%</h3>
              <p>Highest resume match found</p>
            </div>
          </div>

          {loadingHistory && <p className="loading-text">Loading history...</p>}

          {!loadingHistory && history.length === 0 && (
            <div className="empty-box">
              <h2>No history found</h2>
              <p>Analyze your first resume to see reports here.</p>

              <button
                className="download-btn"
                onClick={() => setActivePage("analyzer")}
              >
                Go to Analyzer
              </button>
            </div>
          )}

          <div className="history-list">
            {history.map((item) => (
              <div className="history-card" key={item.id}>
                <div className="history-top">
                  <div>
                    <h2>{item.match_score}% Match</h2>
                    <p>{new Date(item.created_at).toLocaleString()}</p>
                  </div>

                  <div className="history-actions">
                    <span
                      className={`score-label ${getScoreClass(
                        item.match_score
                      )}`}
                    >
                      {getScoreLabel(item.match_score)}
                    </span>

                    <button
                      className="download-btn small-download"
                      onClick={() => downloadReport(item, "history")}
                    >
                      Download
                    </button>

                    <button
                      className="download-btn small-download dark-download"
                      onClick={() => copyReport(item, "history")}
                    >
                      Copy
                    </button>
                  </div>
                </div>

                <div className="history-skill-grid">
                  <div>
                    <h3>Matched Skills</h3>

                    <div className="skills success-skills">
                      {normalizeList(item.matched_skills_list).length > 0 ? (
                        normalizeList(item.matched_skills_list).map(
                          (skill, index) => <span key={index}>{skill}</span>
                        )
                      ) : (
                        <p>No matched skills found.</p>
                      )}
                    </div>
                  </div>

                  <div>
                    <h3>Missing Skills</h3>

                    <div className="skills danger-skills">
                      {normalizeList(item.missing_skills_list).length > 0 ? (
                        normalizeList(item.missing_skills_list).map(
                          (skill, index) => <span key={index}>{skill}</span>
                        )
                      ) : (
                        <p>No missing skills found.</p>
                      )}
                    </div>
                  </div>
                </div>

                <div className="roadmap-card history-roadmap">
                  <h3>Roadmap Preview</h3>

                  <ul>
                    {getRoadmapList(item).length > 0 ? (
                      getRoadmapList(item)
                        .slice(0, 3)
                        .map((roadmapItem, index) => (
                          <li key={index}>{roadmapItem}</li>
                        ))
                    ) : (
                      <li>No roadmap available.</li>
                    )}
                  </ul>
                </div>
              </div>
            ))}
          </div>
        </section>
      </div>
    );
  }

  return (
    <div className="app">
      <div className="black-gradient"></div>
      <Navbar />

      <section className="hero">
        <div className="hero-content">
          <span className="badge">Smart Resume Screening Tool</span>

          <h1>
            Check how well your resume matches any{" "}
            <span>job description.</span>
          </h1>

          <p>
            Upload your resume PDF, paste a job description, and get instant
            match score, matched skills, missing skills, downloadable report,
            and a personalized learning roadmap.
          </p>

          <div className="hero-stats">
            <div>
              <h3>PDF</h3>
              <p>Resume parsing</p>
            </div>

            <div>
              <h3>%</h3>
              <p>Match score</p>
            </div>

            <div>
              <h3>Report</h3>
              <p>Download result</p>
            </div>
          </div>
        </div>

        <div className="hero-info-card">
          <h3>What it analyzes</h3>

          <ul>
            <li>Resume skills against job requirements</li>
            <li>Matched and missing technical skills</li>
            <li>Role readiness for fresher jobs</li>
            <li>Learning roadmap for missing skills</li>
            <li>Downloadable resume match report</li>
          </ul>
        </div>
      </section>

      <section className="main-section">
        <div className="analyzer-card">
          <div className="section-title">
            <span>01</span>

            <div>
              <h2>Upload & Analyze</h2>
              <p>Upload your resume PDF and paste job description.</p>
            </div>
          </div>

          <div className="sample-section">
            <h3>Try Sample Job Descriptions</h3>

            <div className="sample-grid">
              {SAMPLE_JOB_DESCRIPTIONS.map((sample, index) => (
                <button
                  type="button"
                  className="sample-btn"
                  key={index}
                  onClick={() => {
                    setJobDescription(sample.text);
                    setError("");
                    setSuccessMessage(`Loaded sample: ${sample.title}`);
                    setTimeout(() => setSuccessMessage(""), 2500);
                  }}
                >
                  {sample.title}
                </button>
              ))}
            </div>
          </div>

          <form onSubmit={handleAnalyze}>
            <label>Resume PDF</label>

            <div className="upload-box">
              <input
                id="resume-upload"
                type="file"
                accept="application/pdf"
                onChange={(e) => setResume(e.target.files[0])}
              />

              <div className="file-info">
                <h4>{resume ? resume.name : "Choose your resume file"}</h4>
                <p>Only PDF format is supported</p>
              </div>
            </div>

            <label>Job Description</label>

            <textarea
              placeholder="Paste job description here or use a sample above."
              value={jobDescription}
              onChange={(e) => setJobDescription(e.target.value)}
            ></textarea>

            <div className="form-actions">
              <button type="submit" disabled={loading}>
                {loading ? "Analyzing Resume..." : "Analyze Resume"}
              </button>

              <button
                type="button"
                className="download-btn reset-btn"
                onClick={resetAnalyzer}
              >
                Reset
              </button>
            </div>
          </form>

          {error && <p className="error">{error}</p>}
          {successMessage && <p className="success-message">{successMessage}</p>}
        </div>

        <div className="result-panel">
          {!result ? (
            <div className="empty-result">
              <div className="score-placeholder">%</div>

              <h2>Your match report will appear here</h2>

              <p>
                Upload a resume and paste a job description to generate match
                score, matched skills, missing skills, roadmap, and downloadable
                report.
              </p>
            </div>
          ) : (
            <div className="result-card">
              <div className="result-header">
                <div>
                  <span>Analysis Result</span>
                  <h2>Resume Match Report</h2>
                </div>

                <div className="result-actions">
                  <span className={`score-label ${getScoreClass(currentScore)}`}>
                    {getScoreLabel(currentScore)}
                  </span>

                  <button
                    className="download-btn"
                    onClick={() => downloadReport(result, "current")}
                  >
                    Download Report
                  </button>

                  <button
                    className="download-btn dark-download"
                    onClick={() => copyReport(result, "current")}
                  >
                    Copy
                  </button>
                </div>
              </div>

              <div className="score-card">
                <div className="score-circle">
                  <h1>{currentScore}%</h1>
                  <p>Match Score</p>
                </div>

                <div className="score-text">
                  <h3>{getScoreLabel(currentScore)}</h3>
                  <p>
                    This score is calculated by comparing skills detected from
                    your resume with skills required in the job description.
                  </p>
                </div>
              </div>

              <div className="result-grid">
                <div className="mini-card">
                  <h3>Matched Skills</h3>

                  <div className="skills success-skills">
                    {normalizeList(result.analysis.matched_skills_list).length >
                    0 ? (
                      normalizeList(result.analysis.matched_skills_list).map(
                        (skill, index) => <span key={index}>{skill}</span>
                      )
                    ) : (
                      <p>No matched skills found.</p>
                    )}
                  </div>
                </div>

                <div className="mini-card">
                  <h3>Missing Skills</h3>

                  <div className="skills danger-skills">
                    {normalizeList(result.analysis.missing_skills_list).length >
                    0 ? (
                      normalizeList(result.analysis.missing_skills_list).map(
                        (skill, index) => <span key={index}>{skill}</span>
                      )
                    ) : (
                      <p>No missing skills. Good match!</p>
                    )}
                  </div>
                </div>
              </div>

              <div className="roadmap-card">
                <h3>Suggested Learning Roadmap</h3>

                <ul>
                  {getRoadmapList(result.analysis).length > 0 ? (
                    getRoadmapList(result.analysis).map((item, index) => (
                      <li key={index}>{item}</li>
                    ))
                  ) : (
                    <li>No roadmap available.</li>
                  )}
                </ul>
              </div>

              <div className="resume-skills-card">
                <h3>Skills Detected From Resume</h3>

                <div className="skills neutral-skills">
                  {normalizeList(result.resume_skills).length > 0 ? (
                    normalizeList(result.resume_skills).map((skill, index) => (
                      <span key={index}>{skill}</span>
                    ))
                  ) : (
                    <p>No skills detected from resume.</p>
                  )}
                </div>
              </div>

              <div className="resume-skills-card">
                <h3>Skills Required In Job Description</h3>

                <div className="skills neutral-skills">
                  {normalizeList(result.job_description_skills).length > 0 ? (
                    normalizeList(result.job_description_skills).map(
                      (skill, index) => <span key={index}>{skill}</span>
                    )
                  ) : (
                    <p>No job description skills detected.</p>
                  )}
                </div>
              </div>
            </div>
          )}
        </div>
      </section>
    </div>
  );
}

export default App;